/**
 * Where everything `awt` generates for a site goes: one directory, `<site>/build/`.
 *
 *     wiki/site/
 *       package.json  bun.lock  README.md  .gitignore     tracked
 *       node_modules/                                      Quartz's install, where bun puts it
 *       build/                                             everything awt generates
 *         .gitignore                                       `*`, so nothing else has to list it
 *         awt-index.json  quartz.config.yaml  quartz.offline.yaml
 *         dev/                                             `awt site serve`
 *         published/<slug>/                                `awt site publish`, one per target
 *         handoff/                                         `awt site publish --offline`
 *
 * It follows Gradle's `build/`, and for the same reason: a project's own ignore file should not have to
 * know what a tool writes, and every feature that writes something new should not add a line to every
 * repository that uses it. The directory ignores itself, the way pytest's and ruff's caches do, so a repo
 * needs no entry for it at all and `clean` is removing one directory. It sits in the site directory and not
 * at the project root because a root `build/` is Gradle's, and a project can be both.
 *
 * Before this, each of those was a loose file or directory beside `package.json`, with a line of its own in
 * every `.gitignore`: `.awt-index.json`, `.quartz.config.yaml`, `public/`, `release/`, `releases/`, `handoff/`
 * and six hidden staging directories. `LEGACY` names them, so setup can say which are left over and `clean`
 * can remove them.
 */
import fs from "node:fs"
import path from "node:path"

export const BUILD = "build"
export const INDEX = `${BUILD}/awt-index.json`
export const DERIVED = `${BUILD}/quartz.config.yaml`
export const OFFLINE = `${BUILD}/quartz.offline.yaml`
export const DEV = `${BUILD}/dev`
export const PUBLISHED = `${BUILD}/published`
export const HANDOFF = `${BUILD}/handoff`

/** What awt generated beside `package.json` before there was a `build/`. */
export const LEGACY = [
  ".awt-index.json",
  ".quartz.config.yaml",
  ".quartz.offline.yaml",
  "public",
  "release",
  "releases",
  "handoff",
  ".release-staging",
  ".release-prev",
  ".release-work",
  ".release-next",
  ".handoff-staging",
  ".handoff-prev",
]

const SELF_IGNORE = "# Generated by awt. Everything in this directory can be rebuilt, and this file ignores the\n# directory itself, so no .gitignore elsewhere has to name any of it.\n*\n"

/** Create `<site>/build/` with the file that ignores it. Safe to call before every write. */
export function ensureBuildDir(site) {
  const dir = path.join(site, BUILD)
  fs.mkdirSync(dir, { recursive: true })
  const ignore = path.join(dir, ".gitignore")
  if (!fs.existsSync(ignore)) fs.writeFileSync(ignore, SELF_IGNORE)
  return dir
}

/** Where the published site for a target goes: one directory per base, or `default` when none is named. */
export const publishedDir = (site, slug) => path.join(site, PUBLISHED, slug || "default")

/** Which of the old loose files and directories exist in `site`. */
export const legacyPresent = (site) => LEGACY.filter((name) => fs.existsSync(path.join(site, name)) || fs.lstatSync(path.join(site, name), { throwIfNoEntry: false }))

/** Remove them, and report what went. Only the names in `LEGACY`, never anything else in the directory. */
export function removeLegacy(site) {
  const gone = legacyPresent(site)
  for (const name of gone) fs.rmSync(path.join(site, name), { recursive: true, force: true })
  return gone
}

/** Remove `build/` altogether. Returns whether there was one. */
export function cleanBuild(site) {
  const dir = path.join(site, BUILD)
  const had = fs.existsSync(dir)
  fs.rmSync(dir, { recursive: true, force: true })
  return had
}
