/**
 * Build a wiki site for publication, into `<site>/release`.
 *
 * A RELEASE IS THE BUILD OUTPUT ITSELF, kept on disk — not a tag, not a pointer
 * to a commit, and nothing enters git. A wiki is edited daily, so a release
 * marker on that history would be noise; what other wikis actually read is a
 * built directory. That is why this command exists rather than a documented
 * `git tag` ritual.
 *
 * PUBLISH MODE IS A BUILD WITHOUT `--serve`. There is no publish flag: the
 * cross-wiki resolver picks its mode from `ctx.argv.serve`, so a build without
 * it emits every registry entry's `published` base URL, and a dev server emits
 * `dev` ones. The mode being unforgettable is the point — see index.js.
 *
 * IT BUILDS INTO A STAGING DIRECTORY AND RENAMES. Quartz cleans and rewrites
 * its output directory in full before it can know whether the build succeeds,
 * so building straight into `release/` would let a build that dies halfway
 * destroy the release that was standing — the one thing other wikis resolve
 * their links against. Staging is a sibling of the release, so the swap is a
 * rename on one filesystem rather than a copy.
 *
 * IT REFUSES TO BUILD OVER `site/public`, which is the dev server's output.
 * Publish mode over a dev build silently rewrites every cross-wiki link to its
 * published form and vice versa; the pages keep serving and every one returns
 * 200, so the damage is invisible. This avoids the same trap by building into a
 * staging directory and renaming it into place.
 *
 * IT ALSO BUILDS A HANDOFF COPY (`--offline`), for readers who have no server
 * at all — a folder to zip and send, opened by double-clicking index.html on any
 * machine. Two things separate that from a release, and both are unavoidable
 * rather than chosen: `file://` runs no external module script and blocks
 * `fetch`, so every piece of Quartz's JavaScript is dead there; and it has no
 * `try $uri.html` layer, so Quartz's extensionless links resolve to nothing. The
 * first is answered by building with the browser-only plugins off, so the pages
 * carry no dead furniture; the second by rewriting every href to a real file
 * afterwards, because Quartz cannot be configured to emit the extension —
 * `transformLink` drops it unconditionally, and the links in the page chrome are
 * generated by components at render time, out of reach of any transformer.
 *
 * Usage, from anywhere inside a project (`awt` resolves --wiki and --site from
 * the project's awt.config.mjs; the legacy `docs/wiki` + `site` still resolves):
 *     awt publish                        # build, then swap into site/release
 *     awt publish --offline              # a zip-and-send copy, into site/handoff
 *     awt publish --wiki path --site path
 *     awt publish --out path             # somewhere other than site/release
 *     awt publish --nginx                # print a server block and exit
 *
 * The output is static HTML and assets; nothing of Quartz runs at serve time.
 * The one thing a host must do is try `$uri.html` before returning 404, because
 * Quartz emits extensionless URLs — the same resolution rule `awt check`
 * applies on disk, so a site that passes the check is a site nginx serves.
 *
 * Needs `node` and a Quartz clone set up by `awt bootstrap-quartz`.
 */

import fs from "node:fs"
import path from "node:path"
import { spawnSync } from "node:child_process"
import { parseArgs } from "node:util"
import { fileURLToPath } from "node:url"

import { requireProjectRoot } from "./project-root.js"
import { loadFromQuartz } from "./quartz-deps.js"
import { prerenderDiagrams } from "./diagrams-pass.js"

/** The toolbox root: packages/publish/lib -> packages/publish -> packages -> root. */
const HERE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..")

// npm exports npm_config_* into child environments, and npm_config_local_prefix
// makes a nested node/npx resolve against the wrong project. Same hazard as in
// the other two CLIs.
const CLEAN_ENV = Object.fromEntries(
  Object.entries(process.env).filter(([k]) => !k.toUpperCase().startsWith("NPM_")),
)

// The plugins that need a browser to do anything. Off, they render nothing —
// which is the point: left on, a handoff copy shows an empty graph panel, an
// empty explorer heading and a search box that does not answer, and a reader
// with no console concludes the document is broken. og-image is not one of
// them; it is dropped because nothing offline reads a social preview and it is
// most of the build's weight.
const BROWSER_ONLY_PLUGINS = [
  "graph",
  "search",
  "explorer",
  "darkmode",
  "reader-mode",
  "encrypted-pages",
  "stacked-pages",
  "comments",
  "og-image",
]

const CANONICAL_CONFIG = "../quartz.config.yaml"

function run(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { encoding: "utf8", env: CLEAN_ENV, ...opts })
}

function die(msg) {
  console.error(msg)
  process.exit(2)
}

/** Every file under `dir`, as [count, bytes]. */
function measure(dir) {
  let files = 0
  let pages = 0
  let bytes = 0
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) {
      const [f, pg, b] = measure(p)
      files += f
      pages += pg
      bytes += b
    } else if (e.isFile()) {
      files++
      if (e.name.endsWith(".html")) pages++
      bytes += fs.statSync(p).size
    }
  }
  return [files, pages, bytes]
}

/** The shorter of the absolute and cwd-relative forms, so hints stay readable. */
function show(p) {
  const rel = path.relative(process.cwd(), p)
  return rel && rel.length < p.length && !rel.startsWith("..") ? rel : p
}

function mb(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

/**
 * Warn about a base URL that only makes sense locally. Quartz writes it into
 * absolute URLs — the sitemap, the RSS feed, `og:` tags — which a reader never
 * clicks and a crawler always does, so a localhost value here fails silently and
 * only off-site. Regex rather than a YAML parser: this tool has no dependencies,
 * and being wrong costs a missing warning, not a bad build.
 */
function checkBaseUrl(site) {
  const config = path.join(site, "quartz.config.yaml")
  if (!fs.existsSync(config)) return
  const m = /^\s*baseUrl:\s*(.*)$/m.exec(fs.readFileSync(config, "utf8"))
  const value = m ? m[1].trim().replace(/^["']|["']$/g, "").replace(/\s+#.*$/, "") : ""
  if (!value || value === "null" || /^(https?:\/\/)?(localhost|127\.0\.0\.1)\b/.test(value)) {
    console.log(
      `\n⚠ baseUrl in quartz.config.yaml is ${value ? `"${value}"` : "unset"}. The sitemap, RSS\n` +
        "  and og: tags in this release carry it. Set it to the host that serves the release.",
    )
  }
}

/** The wiki's own name, for the note that travels with a handoff copy. */
function siteTitle(site) {
  const config = path.join(site, "quartz.config.yaml")
  const m = fs.existsSync(config)
    ? /^\s*pageTitle:\s*(.*)$/m.exec(fs.readFileSync(config, "utf8"))
    : null
  const value = m ? m[1].trim().replace(/^["']|["']$/g, "") : ""
  return value || "wiki"
}

/** A server block for the host rule Quartz's extensionless URLs need. */
function nginx(root) {
  return `# Quartz output is static: nothing of it runs at serve time. The one rule a
# host must apply is trying $uri.html before 404, because Quartz emits
# extensionless URLs. Without it every internal link 404s.
server {
    listen 80;
    server_name wiki.example.org;

    root ${root};
    index index.html;

    location / {
        try_files $uri $uri.html $uri/index.html =404;
    }

    # Quartz fingerprints its own CSS and JS (component-<hash>.css,
    # postscript-<hash>.js), so those are safe to cache hard. Nothing else is:
    # the pages, static/contentIndex.json and the feeds keep their names and are
    # rewritten by every build.
    location ~ "-[0-9a-f]{8}\\.(css|js)$" {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_page 404 /404.html;
}`
}

/**
 * Quartz reads its config from `<cwd>/quartz.config.yaml` and nothing else —
 * there is no --config flag — so building with a different plugin set means
 * repointing the symlink `awt bootstrap-quartz` created, for the duration of one
 * build. Restored in a `finally`, and verified afterwards.
 *
 * The danger this creates is a wrong-config build that looks right, which is why
 * `assertCanonicalConfig` runs before an ordinary publish: a run killed between
 * the relink and the restore cannot silently produce a release built as a
 * handoff copy — the next publish refuses instead.
 */
function withConfig(quartz, configName, fn) {
  const link = path.join(quartz, "quartz.config.yaml")
  if (!configName) return fn()
  fs.rmSync(link, { force: true })
  fs.symlinkSync(`../${configName}`, link)
  try {
    return fn()
  } finally {
    fs.rmSync(link, { force: true })
    fs.symlinkSync(CANONICAL_CONFIG, link)
  }
}

function assertCanonicalConfig(quartz) {
  const link = path.join(quartz, "quartz.config.yaml")
  const stat = fs.lstatSync(link, { throwIfNoEntry: false })
  // A real file there is somebody's own arrangement, not ours to judge; only a
  // symlink pointing somewhere unexpected means an offline build left it behind.
  if (!stat?.isSymbolicLink()) return
  const target = fs.readlinkSync(link)
  if (target !== CANONICAL_CONFIG) {
    die(
      `${link}\n  points at ${target}, not ${CANONICAL_CONFIG}.\n` +
        "An interrupted --offline build leaves it that way, and publishing now would\n" +
        "build a release with the handoff plugin set and no sign of it. Run\n" +
        "`awt bootstrap-quartz` to put it back.",
    )
  }
}

function build(quartz, wiki, out, configName) {
  process.stdout.write(
    configName
      ? `building (offline mode, ${configName}) ... `
      : "building (publish mode, no --serve) ... ",
  )
  const b = withConfig(quartz, configName, () =>
    run("node", ["quartz/bootstrap-cli.mjs", "build", "-d", path.relative(quartz, wiki), "-o", out], {
      cwd: quartz,
    }),
  )
  if (b.status !== 0) {
    console.log("FAILED")
    die(
      `quartz build failed. The standing release is untouched; the build is left at ${show(out)}:\n` +
        ((b.stdout ?? "") + (b.stderr ?? "")).slice(-2000),
    )
  }
  console.log("ok")
}

/**
 * A release other wikis can resolve against needs more than "the build exited
 * 0": `contentIndex.json` is the file a dependent wiki's registry reads by path,
 * so a release missing it resolves nothing and warns in someone else's build.
 * Checked before the swap, while the previous release is still standing.
 */
function verify(staging, offline) {
  const standing = `The standing release is untouched; the build is left at ${show(staging)}.`
  // contentIndex.json is what a dependent wiki's registry reads by path; a
  // handoff copy has no dependents, and nothing offline can fetch it anyway.
  const required = offline ? ["index.html"] : ["index.html", path.join("static", "contentIndex.json")]
  for (const r of required) {
    if (!fs.existsSync(path.join(staging, r))) {
      die(
        `the build produced no ${r}; not swapping.\n` +
          `Other wikis resolve links against it.\n${standing}`,
      )
    }
  }
  const [files, pages, bytes] = measure(staging)
  if (pages === 0) die(`the build produced no pages; not swapping.\n${standing}`)
  console.log(`  ${pages} pages, ${files} files, ${mb(bytes)}`)
}

/**
 * Swap staging into place, keeping what was there as `.release-prev`. Two
 * renames on one filesystem: the window in which the release path does not
 * exist is between them, and a copy would have no such property at all.
 *
 * The previous release is kept rather than deleted — it is the only copy of what
 * the site served a minute ago, and rolling back is then a rename rather than a
 * rebuild from a working tree that has since moved on.
 */
function swap(staging, out, prev) {
  fs.rmSync(prev, { recursive: true, force: true })
  const had = fs.existsSync(out)
  if (had) fs.renameSync(out, prev)
  fs.renameSync(staging, out)
  return had
}


// ---------------------------------------------------------------- offline mode

/**
 * The config a handoff build uses: the project's own `quartz.offline.yaml` if it
 * has one, else one derived from `quartz.config.yaml` with the browser-only
 * plugins turned off. Derived by default because the interesting choice is
 * *which* plugins those are, and that answer is the same in every project;
 * a project that disagrees writes the file and owns it from then on.
 *
 * Parsed with the `yaml` inside the Quartz clone — the same parser Quartz reads
 * the config with, so this cannot disagree with it about what the file says.
 *
 * Returns the file name, relative to `site/`, since that is what the symlink
 * inside the clone has to name.
 */
async function offlineConfig(site, quartz) {
  const own = "quartz.offline.yaml"
  if (fs.existsSync(path.join(site, own))) {
    console.log(`config: ${own} (the project's own)`)
    return own
  }

  const { parse, stringify } = await loadFromQuartz(quartz, "yaml", die)
  const config = parse(fs.readFileSync(path.join(site, "quartz.config.yaml"), "utf8"))

  config.configuration ??= {}
  // Both are progressive enhancement over `file://` and worse than useless
  // there: the SPA router would intercept clicks it cannot then service.
  config.configuration.enableSPA = false
  config.configuration.enablePopovers = false

  const off = []
  for (const plugin of config.plugins ?? []) {
    const source = typeof plugin.source === "string" ? plugin.source : plugin.source?.name
    const name = String(source ?? "").split("/").pop()
    if (BROWSER_ONLY_PLUGINS.includes(name) && plugin.enabled !== false) {
      plugin.enabled = false
      off.push(name)
    }
  }

  const generated = `.${own}`
  fs.writeFileSync(
    path.join(site, generated),
    "# GENERATED by awt publish --offline. Do not edit: it is rewritten on\n" +
      "# every offline build, and the comments in quartz.config.yaml are lost in\n" +
      "# the round trip. To take this over, copy it to quartz.offline.yaml;\n" +
      "# awt publish uses that instead, and never touches it.\n" +
      stringify(config),
  )
  console.log(`config: ${generated} (derived; ${off.length ? off.join(", ") + " off" : "nothing to turn off"})`)
  return generated
}

/**
 * Rewrite an ordinary Quartz build into one that opens from `file://`.
 *
 * `file://` has no host applying `try $uri.html`, so an extensionless href
 * resolves to nothing at all — and Quartz has no setting for the extension.
 * Every link exists in one form only in the emitted HTML, which is why this
 * happens here rather than in a plugin: the links in breadcrumbs, backlinks,
 * folder listings and the table of contents are built by components at render
 * time, after every transformer has run.
 *
 * Attributes are rewritten in place rather than by parsing and re-serialising
 * the document, so nothing else in the file can change: an HTML round trip
 * normalises entities and void elements, and the diff would be unreviewable.
 *
 * A LINK THAT DOES NOT RESOLVE IS NOT AUTOMATICALLY A DEFECT. Most are
 * placeholders — `[[notes]]` nobody has written yet, which every working wiki
 * has a backlog of, and which Quartz itself marks `class="… broken"`. Failing on
 * those would mean no wiki with a backlog could ever be handed to a reader; it is
 * the same mistake as asserting zero broken links, which `awt check` exists to
 * not make. They are neutralised instead: the destination moves to
 * `data-unresolved-href`, so the text still reads but nothing lands the reviewer
 * on a browser error page they cannot interpret.
 *
 * A missing `src` is treated as a defect and does fail, because an asset the
 * build was supposed to emit and did not is a broken build, not a backlog.
 */
function toFileUrls(root) {
  const walk = (d) =>
    fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => {
      const p = path.join(d, e.name)
      return e.isDirectory() ? walk(p) : [p]
    })
  const all = walk(root)
  const pages = all.filter((f) => f.endsWith(".html"))

  // What a browser can actually open from disk: an exact file, nothing else.
  // A directory is not it — `file://` shows a listing rather than its index.
  const resolve = (dir, link) => {
    const disk = path.join(dir, decodeURIComponent(link))
    if (fs.existsSync(disk) && fs.statSync(disk).isFile()) return link
    if (fs.existsSync(disk + ".html")) return link + ".html"
    if (fs.existsSync(path.join(disk, "index.html"))) return link.replace(/\/?$/, "/") + "index.html"
    return null
  }

  const external = (u) => !u || /^[a-z][a-z0-9+.-]*:/i.test(u) || u.startsWith("#") || u.startsWith("//")

  let rewritten = 0
  let scripts = 0
  let neutralised = 0
  const placeholders = new Set()
  const dangling = []
  const missingAssets = []

  for (const page of pages) {
    const dir = path.dirname(page)
    const before = fs.readFileSync(page, "utf8")
    // Strip the scripts outright. None of them can run from `file://`, and a
    // handoff copy that provably carries no JavaScript is easier to hand over
    // than one that carries some which happens not to execute.
    let html = before.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, () => {
      scripts++
      return ""
    })
    // Quartz preloads its scripts as well as loading them. Left behind, the
    // preload keeps the bundle it points at alive as a referenced file, so a
    // copy advertised as carrying no JavaScript still ships some.
    html = html.replace(/<link\b[^>]*\b(?:as="script"|rel="modulepreload")[^>]*>/gi, () => {
      scripts++
      return ""
    })

    const rewrite = (whole, attr, url, tag) => {
      if (external(url)) return whole
      const [link, anchor = ""] = url.split(/(#.*)$/)
      if (!link) return whole
      const target = resolve(dir, link)
      if (target) {
        if (target === link) return whole
        rewritten++
        return `${attr}="${target}${anchor}"`
      }

      if (attr === "src") {
        missingAssets.push(`${path.relative(root, page)} -> ${url}`)
        return whole
      }
      // Quartz already knows: it renders a link to an unwritten note with the
      // `broken` class. Trusting that mark rather than re-deciding keeps this
      // agreeing with the renderer instead of second-guessing it.
      if (/\bclass="[^"]*\bbroken\b/.test(tag)) {
        placeholders.add(link.replace(/^(\.\.?\/)+/, ""))
      } else {
        dangling.push(`${path.relative(root, page)} -> ${url}`)
      }
      neutralised++
      return `data-unresolved-href="${url}"`
    }

    html = html.replace(/(?<![\w-])(href|src)="([^"]*)"/g, (whole, attr, url, offset) => {
      // The enclosing tag, so the class attribute is visible whether it sits
      // before or after the attribute being rewritten.
      const start = html.lastIndexOf("<", offset)
      const end = html.indexOf(">", offset)
      const tag = start === -1 || end === -1 ? "" : html.slice(start, end + 1)
      return rewrite(whole, attr, url, tag)
    })
    // An alias emits a meta refresh, whose destination is a link like any other
    // and would otherwise send the reader to a page that does not exist.
    html = html.replace(
      /(content)="(\d+\s*;\s*url=)([^"]+)"/gi,
      (whole, attr, prefix, url) => {
        const inner = rewrite(`${attr}="${url}"`, attr, url)
        return inner === `${attr}="${url}"` ? whole : `${attr}="${prefix}${inner.slice(attr.length + 2, -1)}"`
      },
    )

    if (html !== before) fs.writeFileSync(page, html)
  }

  // With every script tag gone, the chunks they loaded are unreachable weight.
  let removed = 0
  const referenced = new Set()
  for (const page of pages) {
    for (const m of fs.readFileSync(page, "utf8").matchAll(/(?<![\w-])(?:href|src)="([^"]+)"/g)) {
      if (!external(m[1])) {
        referenced.add(path.resolve(path.dirname(page), decodeURIComponent(m[1].split("#")[0])))
      }
    }
  }
  for (const f of all) {
    if (f.endsWith(".js") && !referenced.has(path.resolve(f))) {
      fs.rmSync(f)
      removed++
    }
  }
  for (const d of walk_dirs(root)) {
    if (fs.readdirSync(d).length === 0) fs.rmdirSync(d)
  }

  return {
    pages: pages.length,
    rewritten,
    scripts,
    removed,
    neutralised,
    placeholders: [...placeholders].sort(),
    dangling,
    missingAssets,
  }
}

/**
 * Make the front door a real page.
 *
 * A wiki whose landing note is not literally `index.md` — `README.md`, say —
 * gets an `index.html` from Quartz that is a 246-byte `<meta http-equiv=
 * "refresh">` stub pointing at the real page. Over HTTP that is invisible. Handed
 * to a reviewer as a folder, it is the first thing they double-click, and a
 * refresh is exactly the kind of navigation a browser may decline to perform
 * from `file://` — leaving a blank window with nothing to click and no error to
 * read. Inlining the target removes the hop entirely.
 *
 * Only when the target sits in the same directory, because every relative link
 * inside it is written from that directory's depth and would otherwise resolve
 * one level off — a page that loads with every link subtly wrong is worse than
 * a redirect.
 */
function inlineRootIndex(root) {
  const index = path.join(root, "index.html")
  if (!fs.existsSync(index)) return null
  const html = fs.readFileSync(index, "utf8")
  const m = /<meta\s+http-equiv="refresh"\s+content="\d+\s*;\s*url=([^"]+)"/i.exec(html)
  if (!m) return null
  // A stub is head-only. Anything with real content is a page in its own right.
  if (/<body[^>]*>\s*\S/i.test(html)) return null

  const target = decodeURIComponent(m[1].split("#")[0])
  if (path.dirname(target) !== "." || !fs.existsSync(path.join(root, target))) return null

  fs.copyFileSync(path.join(root, target), index)
  return target
}

/** Directories under `root`, deepest first, so emptied ones can be dropped. */
function walk_dirs(root) {
  const out = []
  const visit = (d) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      if (e.isDirectory()) {
        const p = path.join(d, e.name)
        visit(p)
        out.push(p)
      }
    }
  }
  visit(root)
  return out
}

/**
 * Every reference a browser will follow must be a file that exists. This is the
 * whole guarantee of a handoff copy — there is no server to be forgiving, and a
 * reader who clicks into a "file not found" has no way to tell it from the
 * document being broken.
 */
function verifyFileUrls(root) {
  const bad = []
  let total = 0
  const walk = (d) =>
    fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => {
      const p = path.join(d, e.name)
      return e.isDirectory() ? walk(p) : p.endsWith(".html") ? [p] : []
    })
  for (const page of walk(root)) {
    const dir = path.dirname(page)
    for (const m of fs.readFileSync(page, "utf8").matchAll(/(?<![\w-])(?:href|src)="([^"]+)"/g)) {
      const url = m[1]
      if (!url || /^[a-z][a-z0-9+.-]*:/i.test(url) || url.startsWith("#") || url.startsWith("//")) continue
      const link = url.split("#")[0]
      if (!link) continue
      total++
      const disk = path.join(dir, decodeURIComponent(link))
      if (!fs.existsSync(disk) || !fs.statSync(disk).isFile()) bad.push(`${path.relative(root, page)} -> ${url}`)
    }
  }
  return { total, bad }
}

/**
 * A note for the person receiving the folder, who did not ask for any of this.
 * The zip warning is not hypothetical: Windows lets you browse a zip in place
 * and double-click a file inside it, which extracts that one file to a temp
 * directory, and every relative link in it then points at nothing.
 */
function handoffReadme(title) {
  return `${title}\n${"=".repeat(title.length)}\n
A snapshot of the wiki, for reading offline.

1. EXTRACT this folder from the zip first. Do not open the pages inside the zip
   itself: Windows extracts one page on its own and every link breaks.
2. Open index.html (double-click it). Any browser will do, and nothing has to be
   installed.

Every page is an ordinary HTML file, so the links work with no internet
connection and no server. There is no search box: start at index.html, and use
the links and the trail at the top of each page to move around.
`
}

export async function publish(argv = process.argv.slice(2)) {
  let parsed
  try {
    parsed = parseArgs({
      args: argv,
      options: {
        // No defaults: absent means "find the project", which is not the same as
        // "look for ./docs/wiki". parseArgs cannot tell a default from a value.
        wiki: { type: "string" },
        site: { type: "string" },
        out: { type: "string" },
        offline: { type: "boolean", default: false },
        diagrams: { type: "string" },
        nginx: { type: "boolean", default: false },
      },
    })
  } catch (e) {
    die(String(e.message))
  }
  const { values } = parsed

  const root = values.wiki && values.site ? null : requireProjectRoot(die)
  const wiki = values.wiki ? path.resolve(values.wiki) : path.join(root, "docs/wiki")
  const site = values.site ? path.resolve(values.site) : path.join(root, "site")
  // `release` is not a name this tool is free to change: other wikis' registries
  // name `…/site/release/static/contentIndex.json` by path in their own configs.
  const out = values.out
    ? path.resolve(values.out)
    : path.join(site, values.offline ? "handoff" : "release")

  for (const [label, p] of [
    ["wiki", wiki],
    ["site", site],
  ]) {
    if (!fs.existsSync(p)) die(`no ${label} directory at ${p}`)
  }

  // Pre-rendering is for the handoff copy only. A served site keeps mermaid as
  // Quartz ships it: rendered in the reader's browser, where the diagram follows
  // the page's theme and its text stays searchable.
  const diagrams = values.diagrams ?? (values.offline ? "png" : "none")
  if (!["png", "none"].includes(diagrams)) die(`--diagrams takes png or none, not ${diagrams}`)
  if (diagrams === "png" && !values.offline) {
    die("--diagrams png is only for --offline; a served site renders mermaid in the browser.")
  }

  if (values.nginx) {
    console.log(nginx(out))
    return 0
  }

  if (path.resolve(out) === path.join(site, "public")) {
    die(
      "refusing to publish into site/public, the dev server's output. Publish into site/release.",
    )
  }

  const quartz = path.join(site, ".quartz-src")
  if (!fs.existsSync(quartz)) {
    die(`${quartz} missing; the Quartz clone is not set up. Run \`awt bootstrap-quartz\` first.`)
  }
  assertCanonicalConfig(quartz)

  console.log(`wiki: ${wiki}\nsite: ${site}\n${values.offline ? "handoff" : "release"}: ${out}`)
  const configName = values.offline ? await offlineConfig(site, quartz) : null
  console.log()

  const staging = path.join(path.dirname(out), `.${path.basename(out)}-staging`)
  const prev = path.join(path.dirname(out), `.${path.basename(out)}-prev`)

  // A staging directory left by an interrupted run is half a site, and Quartz
  // would build into it rather than over it for files it no longer emits.
  fs.rmSync(staging, { recursive: true, force: true })

  build(quartz, wiki, staging, configName)
  verify(staging, values.offline)

  if (values.offline) {
    if (diagrams === "png") {
      try {
        const d = await prerenderDiagrams(staging, quartz, (m) => console.log(m))
        if (d.diagrams) {
          console.log(`  ${d.diagrams} mermaid diagrams pre-rendered to PNG, replacing ${d.replaced} code blocks`)
        }
        for (const f of d.failed ?? []) {
          console.log(`\n⚠ a mermaid diagram would not render, left as its source text:\n    ${f.error}\n    ${f.source.trim().split("\n")[0]}`)
        }
      } catch (e) {
        die(
          `${String(e.message ?? e)}\n\nRun with --diagrams none to build without them; they stay as\n` +
            `source text. The standing copy is untouched; the build is left at ${show(staging)}.`,
        )
      }
    }

    const r = toFileUrls(staging)
    console.log(
      `  rewrote ${r.rewritten} links to real files, removed ${r.scripts} scripts and ${r.removed} now-unused .js files`,
    )
    if (r.placeholders.length) {
      console.log(
        `  ${r.neutralised - r.dangling.length} links to ${r.placeholders.length} unwritten notes made unclickable: ` +
          r.placeholders.slice(0, 6).join(", ") +
          (r.placeholders.length > 6 ? `, +${r.placeholders.length - 6} more` : ""),
      )
    }
    if (r.dangling.length) {
      // Not a placeholder and not a missing asset: a link the renderer thought
      // it had resolved. It is broken in the release too, and `awt check` is what
      // says so — this only refuses to hide it.
      console.log(
        `\n⚠ ${r.dangling.length} link${r.dangling.length === 1 ? "" : "s"} the renderer did not mark broken\n` +
          "  resolve to nothing. They are broken in the served site too; awt check reports them.\n" +
          "  Made unclickable in this copy:",
      )
      for (const d of r.dangling.slice(0, 10)) console.log(`    ${d}`)
      if (r.dangling.length > 10) console.log(`    … and ${r.dangling.length - 10} more`)
    }
    if (r.missingAssets.length) {
      die(
        `${r.missingAssets.length} images or stylesheets are missing from the build; not swapping.\n` +
          r.missingAssets.slice(0, 10).map((u) => `  ${u}`).join("\n") +
          `\nThe standing copy is untouched; the build is left at ${show(staging)}.`,
      )
    }
    const v = verifyFileUrls(staging)
    if (v.bad.length) {
      die(
        `${v.bad.length} of ${v.total} references cannot be opened from file://; not swapping.\n` +
          v.bad.slice(0, 10).map((u) => `  ${u}`).join("\n"),
      )
    }
    console.log(`  ${v.total} clickable references, all of them files a browser can open from disk`)
    const inlined = inlineRootIndex(staging)
    if (inlined) console.log(`  index.html is ${inlined} itself now, not a redirect to it`)
    fs.writeFileSync(path.join(staging, "README.txt"), handoffReadme(siteTitle(site)))
  }

  const replaced = swap(staging, out, prev)

  console.log(`\n${values.offline ? "built the handoff copy" : "published"} ${show(out)}`)
  if (replaced) {
    const what = values.offline ? "copy" : "release"
    console.log(`  previous ${what} kept at ${show(prev)}; roll back with:  mv ${show(prev)} ${show(out)}`)
  }
  if (values.offline) {
    console.log(
      "\nThe reader extracts the folder and opens index.html; README.txt inside says so.\n" +
        "Search, the graph, the explorer tree and hover previews are absent: they need\n" +
        "JavaScript, which does not run from file://.",
    )
    return 0
  }

  checkBaseUrl(site)
  console.log(
    "\nServe it with any static host that tries $uri.html before 404:\n" +
      "    try_files $uri $uri.html $uri/index.html =404;\n" +
      "A full nginx server block:  awt publish --nginx\n" +
      "\nThe graph is verified in two places, neither of them this command:\n" +
      "    awt check                the links on disk\n" +
      "    the awt-links shadow     the rendered pages, during the build above",
  )
  return 0
}
